development:
  adapter: postgresql
  encoding: unicode
  database: re_demo_rails_dev
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: re_demo_rails_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: re_demo_rails_prod
  pool: 5
  username:
  password:
